# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-09 14:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_date', models.DateTimeField(auto_now_add=True)),
                ('product_city', models.CharField(max_length=31)),
                ('product_zip_code', models.IntegerField()),
                ('product_key', models.CharField(max_length=31, unique=True)),
                ('slug', models.SlugField(help_text='A label for the URL config', max_length=31, unique=True)),
                ('product_type', models.CharField(choices=[('BK', 'BIKE'), ('EL', 'TECHNIK'), ('CA', 'AUTO'), ('OT', 'ANDERE')], default='BK', max_length=2)),
                ('status', models.CharField(choices=[('OW', 'OWNED'), ('NO', 'STOLEN')], default='OW', max_length=2)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['register_date'],
            },
        ),
    ]
