# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-10 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20171009_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_zip_code',
        ),
        migrations.AddField(
            model_name='product',
            name='zip_code',
            field=models.CharField(default=13357, max_length=6),
            preserve_default=False,
        ),
    ]
