# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-11 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_remove_product_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='img',
            field=models.ImageField(default='profiles/profile_pictures/default_profile_picture', upload_to='profiles/profile_pictures'),
        ),
        migrations.AlterField(
            model_name='product',
            name='key',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
