# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-11 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20171011_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(default='C:\\Users\\Computer\\Documents\\Projects\\charlees\\media\\profiles\\profile_pictures\\default_profile_picture.PNG', upload_to='profiles/profile_pictures'),
        ),
    ]
