# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-11 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_auto_20171011_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(default='/profiles/profile_pictures/default_profile_picture.png', upload_to='profiles/profile_pictures'),
        ),
    ]
