# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-21 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0017_auto_20171011_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
