# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-06 06:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0023_auto_20171101_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
