# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0026_remove_profile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='slug',
            field=models.SlugField(blank=True, max_length=30, unique=True),
        ),
    ]
