# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-09 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_date', models.DateTimeField(auto_now_add=True)),
                ('product_city', models.CharField(max_length=31)),
                ('product_zip_code', models.IntegerField()),
                ('product_key', models.CharField(max_length=31, unique=True)),
                ('slug', models.SlugField(help_text='A label for the URL config', max_length=31, unique=True)),
                ('product_type', models.CharField(choices=[('BK', 'BIKE'), ('EL', 'TECHNIK'), ('CA', 'AUTO'), ('OT', 'ANDERE')], default='BK', max_length=2)),
                ('status', models.CharField(choices=[('OW', 'OWNED'), ('NO', 'STOLEN')], default='OW', max_length=2)),
            ],
            options={
                'ordering': ['register_date'],
            },
        ),
    ]
