# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-06 06:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0003_auto_20171009_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_date', models.DateTimeField(auto_now_add=True)),
                ('zip_code', models.CharField(max_length=6)),
                ('key', models.CharField(max_length=6, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='A label for the URL config', max_length=31, unique=True)),
                ('type', models.CharField(choices=[('BK', 'BIKE'), ('EL', 'TECHNIK'), ('CA', 'AUTO'), ('OT', 'ANDERE')], default='BK', max_length=2)),
                ('status', models.CharField(choices=[('OW', 'OWNED'), ('NO', 'STOLEN')], default='OW', max_length=2)),
                ('is_blocked', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['register_date'],
            },
        ),
    ]
